[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "threebody-challenge"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "numpy>=1.24"
]

[tool.pytest.ini_options]
addopts = "-q"
